# run once rake spec_prep
# run often (avoiding download) rake spec_standalone
fixtures:
  forge_modules:
      stdlib: "puppetlabs/stdlib"
      concat: "puppetlabs/concat"
      apt: "puppetlabs/apt"
      ssh: "erwbgy/ssh"
      nfs: "jbeard/nfs"
      portmap: "jbeard/portmap"
      augeasproviders: domcleal/augeasproviders
  repositories:
    dnsmasq:
      repo: git://github.com/ngiger/puppet-dnsmasq.git
      ref: master
  symlinks:
    x2go: "#{source_dir}"
