---
language: ruby
cache: bundler
bundler_args: --without development
#  bundle exec rake lint # crashes with an UTF-8 error. therefore excluding it
# same for bundle exec rake validate &&
script: "bundle exec rake spec SPEC_OPTS='--format documentation' && bundle exec rake clean build"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.2
    env: PUPPET_GEM_VERSION="~> 3.8.6" STRICT_VARIABLES="yes"
